import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../models/match_model.dart';
import '../models/models.dart';

class PDFService {
  // A small, fixed palette of print-friendly accent colors. Each team is
  // deterministically assigned one (by hashing its id) so the same team
  // always gets the same color across exports, and the two teams in a
  // match are guaranteed to get different colors.
  static final List<PdfColor> _teamPalette = [
    _hex(0x1E3A5F), // navy
    _hex(0x9A3412), // rust
    _hex(0x0F5C4C), // forest
    _hex(0x4C1D95), // plum
    _hex(0x9F1D3A), // crimson
    _hex(0x0E7490), // teal
  ];

  static PdfColor _hex(int hex, [double alpha = 1.0]) {
    return PdfColor(((hex >> 16) & 0xFF) / 255, ((hex >> 8) & 0xFF) / 255, (hex & 0xFF) / 255, alpha);
  }

  static List<PdfColor> _teamColors(Team a, Team b) {
    final ia = a.id.hashCode.abs() % _teamPalette.length;
    var ib = b.id.hashCode.abs() % _teamPalette.length;
    if (ib == ia) ib = (ib + 1) % _teamPalette.length;
    return [_teamPalette[ia], _teamPalette[ib]];
  }

  static Future<void> generateScorecard(Match match) async {
    final pdf = pw.Document();

    final battingTeam1 = match.battingTeamFor(true);
    final bowlingTeam1 = match.bowlingTeamFor(true);
    final battingTeam2 = match.battingTeamFor(false);
    final bowlingTeam2 = match.bowlingTeamFor(false);

    final allTeams = [match.teamA, match.teamB];
    final result = match.resultString;

    final teamColors = _teamColors(match.teamA, match.teamB);
    PdfColor colorFor(Team t) => t.id == match.teamA.id ? teamColors[0] : teamColors[1];

    pdf.addPage(
      pw.MultiPage(
        pageTheme: pw.PageTheme(
          pageFormat: PdfPageFormat.a4,
          margin: const pw.EdgeInsets.all(24),
          buildBackground: (context) => pw.FullPage(
            ignoreMargins: true,
            // Small and legible, not a page-dominating billboard.
            child: pw.Watermark(
              child: pw.Text(
                'VISH_CRIC',
                style: pw.TextStyle(
                  fontSize: 30,
                  color: _hex(0xB8860B, 0.10),
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
            ),
          ),
        ),
        footer: (context) => pw.Container(
          margin: const pw.EdgeInsets.only(top: 8),
          padding: const pw.EdgeInsets.only(top: 6),
          decoration: const pw.BoxDecoration(
            border: pw.Border(top: pw.BorderSide(color: PdfColors.grey300, width: 0.5)),
          ),
          child: pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text('Generated by VISH_CRIC', style: const pw.TextStyle(fontSize: 7, color: PdfColors.grey500)),
              pw.Text('Page ${context.pageNumber} of ${context.pagesCount}', style: const pw.TextStyle(fontSize: 7, color: PdfColors.grey500)),
            ],
          ),
        ),
        build: (pw.Context context) => [
          // ─── Header band ────────────────────────────────────────────────
          pw.Container(
            width: double.infinity,
            padding: const pw.EdgeInsets.symmetric(horizontal: 16, vertical: 12),
            decoration: pw.BoxDecoration(color: _hex(0x0A0A0F), borderRadius: pw.BorderRadius.circular(6)),
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              crossAxisAlignment: pw.CrossAxisAlignment.center,
              children: [
                pw.Text('VISH_CRIC', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold, color: _hex(0xFFD700), letterSpacing: 2)),
                pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.end,
                  children: [
                    pw.Text('${match.teamA.name} vs ${match.teamB.name}',
                        style: pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold, color: PdfColors.white)),
                    pw.SizedBox(height: 2),
                    pw.Text('${match.date.toString().split(' ')[0]}   ${match.maxOvers} Overs',
                        style: const pw.TextStyle(fontSize: 8.5, color: PdfColors.grey400)),
                  ],
                ),
              ],
            ),
          ),
          pw.SizedBox(height: 10),

          // ─── Result banner ──────────────────────────────────────────────
          pw.Container(
            width: double.infinity,
            padding: const pw.EdgeInsets.symmetric(horizontal: 12, vertical: 8),
            decoration: pw.BoxDecoration(
              color: _hex(0xFFF8E1),
              borderRadius: pw.BorderRadius.circular(6),
              border: pw.Border.all(color: _hex(0xFFD700), width: 1),
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text('MATCH RESULT', style: pw.TextStyle(fontSize: 7.5, fontWeight: pw.FontWeight.bold, color: _hex(0xB8860B), letterSpacing: 1.5)),
                pw.SizedBox(height: 2),
                pw.Text(result.toUpperCase(), style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold, color: _hex(0x1A1A1A))),
              ],
            ),
          ),
          pw.SizedBox(height: 10),

          // ─── Score summary chips ────────────────────────────────────────
          if (match.innings1 != null)
            pw.Row(
              children: [
                pw.Expanded(
                  child: _scoreChip(battingTeam1.name, match.innings1!.totalRuns, match.innings1!.totalWickets, colorFor(battingTeam1)),
                ),
                if (match.innings2 != null) ...[
                  pw.SizedBox(width: 8),
                  pw.Expanded(
                    child: _scoreChip(battingTeam2.name, match.innings2!.totalRuns, match.innings2!.totalWickets, colorFor(battingTeam2)),
                  ),
                ],
              ],
            ),
          pw.SizedBox(height: 14),

          // ─── Innings 1 ───────────────────────────────────────────────────
          if (match.innings1 != null) ...[
            _sectionHeader(
              'INNINGS 1 · ${battingTeam1.name.toUpperCase()}',
              '${match.innings1!.totalRuns}/${match.innings1!.totalWickets}  (${match.innings1!.legalBalls ~/ 6}.${match.innings1!.legalBalls % 6} ov)',
              colorFor(battingTeam1),
            ),
            _battingTable(match.innings1!, battingTeam1, allTeams),
            _bowlingLabel(bowlingTeam1.name, colorFor(bowlingTeam1)),
            _bowlingTable(match.innings1!, bowlingTeam1),
            pw.SizedBox(height: 16),
          ],

          // ─── Innings 2 ───────────────────────────────────────────────────
          if (match.innings2 != null) ...[
            _sectionHeader(
              'INNINGS 2 · ${battingTeam2.name.toUpperCase()}',
              '${match.innings2!.totalRuns}/${match.innings2!.totalWickets}  (${match.innings2!.legalBalls ~/ 6}.${match.innings2!.legalBalls % 6} ov)',
              colorFor(battingTeam2),
            ),
            _battingTable(match.innings2!, battingTeam2, allTeams),
            _bowlingLabel(bowlingTeam2.name, colorFor(bowlingTeam2)),
            _bowlingTable(match.innings2!, bowlingTeam2),
          ],
        ],
      ),
    );

    final now = DateTime.now();
    final filename = 'VISH_CRIC_${now.day}_${now.month}_${now.year}_${now.hour}_${now.minute}.pdf';

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name: filename,
    );
  }

  // ─── Score chip ─────────────────────────────────────────────────────────
  static pw.Widget _scoreChip(String name, int runs, int wickets, PdfColor color) {
    return pw.Container(
      padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 6),
      decoration: pw.BoxDecoration(color: color, borderRadius: pw.BorderRadius.circular(5)),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(name.toUpperCase(), style: pw.TextStyle(fontSize: 7, fontWeight: pw.FontWeight.bold, color: PdfColors.white, letterSpacing: 0.8)),
          pw.SizedBox(height: 1),
          pw.Text('$runs/$wickets', style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold, color: PdfColors.white)),
        ],
      ),
    );
  }

  // ─── Section header (colored by the batting team) ──────────────────────
  static pw.Widget _sectionHeader(String label, String scoreText, PdfColor color) {
    return pw.Container(
      width: double.infinity,
      decoration: pw.BoxDecoration(
        color: color,
        borderRadius: const pw.BorderRadius.only(topLeft: pw.Radius.circular(5), topRight: pw.Radius.circular(5)),
      ),
      padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 6),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(label, style: pw.TextStyle(fontSize: 9.5, fontWeight: pw.FontWeight.bold, color: PdfColors.white)),
          pw.Text(scoreText, style: pw.TextStyle(fontSize: 9, fontWeight: pw.FontWeight.bold, color: PdfColors.white)),
        ],
      ),
    );
  }

  // ─── Bowling sub-label (colored by the bowling team) ────────────────────
  static pw.Widget _bowlingLabel(String teamName, PdfColor color) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(top: 8, bottom: 4),
      child: pw.Row(
        children: [
          pw.Container(width: 2.5, height: 9, color: color),
          pw.SizedBox(width: 5),
          pw.Text('BOWLING · ${teamName.toUpperCase()}', style: pw.TextStyle(fontSize: 8, fontWeight: pw.FontWeight.bold, color: color, letterSpacing: 1)),
        ],
      ),
    );
  }

  // ─── Table cell helpers ─────────────────────────────────────────────────
  static pw.Widget _cell(String text, {bool bold = false, PdfColor? color, pw.TextAlign align = pw.TextAlign.left}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(horizontal: 4, vertical: 5),
      child: pw.Text(
        text,
        textAlign: align,
        style: pw.TextStyle(fontSize: 7.5, fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal, color: color ?? PdfColors.black),
      ),
    );
  }

  static pw.Widget _badgeOrDash(int count, PdfColor bg, PdfColor fg) {
    if (count <= 0) {
      return pw.Padding(
        padding: const pw.EdgeInsets.symmetric(vertical: 5),
        child: pw.Center(child: pw.Text('0', style: const pw.TextStyle(fontSize: 7.5, color: PdfColors.grey400))),
      );
    }
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 4),
      child: pw.Center(
        child: pw.Container(
          padding: const pw.EdgeInsets.symmetric(horizontal: 5, vertical: 1.5),
          decoration: pw.BoxDecoration(color: bg, borderRadius: pw.BorderRadius.circular(3)),
          child: pw.Text('$count', style: pw.TextStyle(fontSize: 7, fontWeight: pw.FontWeight.bold, color: fg)),
        ),
      ),
    );
  }

  // ─── Batting table ────────────────────────────────────────────────────────
  static pw.Widget _battingTable(Innings innings, Team battingTeam, List<Team> allTeams) {
    final stats = innings.calculateBatterStats(battingTeam);

    final rows = <pw.TableRow>[];
    int i = 0;
    for (final p in battingTeam.players) {
      final s = stats[p.id]!;
      if (s.balls == 0 && !s.dismissed) continue; // Never faced a ball
      final sr = s.balls > 0 ? (s.runs / s.balls * 100).toStringAsFixed(1) : '-';
      final isOut = s.dismissed;
      final dismissalText = isOut ? getHowOutString(s, allTeams) : 'not out';

      rows.add(pw.TableRow(
        decoration: pw.BoxDecoration(color: i.isOdd ? _hex(0xFAFAF5) : PdfColors.white),
        children: [
          _cell(p.name, bold: true),
          _cell('${s.runs}', bold: true, align: pw.TextAlign.right),
          _cell('${s.balls}', color: PdfColors.grey600, align: pw.TextAlign.right),
          _badgeOrDash(s.fours, _hex(0xDBEAFE), _hex(0x1D4ED8)),
          _badgeOrDash(s.sixes, _hex(0xEDE9FE), _hex(0x6D28D9)),
          _cell(sr, color: PdfColors.grey600, align: pw.TextAlign.right),
          _cell(dismissalText, color: isOut ? _hex(0x9F3A3A) : _hex(0x15803D), bold: !isOut),
        ],
      ));
      i++;
    }

    if (rows.isEmpty) {
      return pw.Padding(padding: const pw.EdgeInsets.all(6), child: pw.Text('No batting data', style: const pw.TextStyle(fontSize: 8)));
    }

    return pw.Table(
      border: pw.TableBorder.all(color: _hex(0xECECE4), width: 0.4),
      columnWidths: const {
        0: pw.FlexColumnWidth(2.6),
        1: pw.FlexColumnWidth(0.7),
        2: pw.FlexColumnWidth(0.7),
        3: pw.FlexColumnWidth(0.7),
        4: pw.FlexColumnWidth(0.7),
        5: pw.FlexColumnWidth(0.9),
        6: pw.FlexColumnWidth(3),
      },
      children: [
        pw.TableRow(
          decoration: pw.BoxDecoration(color: _hex(0xF7F5EC)),
          children: ['BATTER', 'R', 'B', '4s', '6s', 'SR', 'DISMISSAL']
              .map((h) => pw.Padding(
                    padding: const pw.EdgeInsets.symmetric(horizontal: 4, vertical: 5),
                    child: pw.Text(h, style: pw.TextStyle(fontSize: 7, fontWeight: pw.FontWeight.bold, color: _hex(0x6B6B63))),
                  ))
              .toList(),
        ),
        ...rows,
      ],
    );
  }

  // ─── Bowling table ────────────────────────────────────────────────────────
  static pw.Widget _bowlingTable(Innings innings, Team bowlingTeam) {
    final stats = innings.calculateBowlerStats(bowlingTeam);
    final entries = stats.entries.where((e) => e.value.balls > 0).toList();

    if (entries.isEmpty) {
      return pw.Padding(padding: const pw.EdgeInsets.all(6), child: pw.Text('No bowling data', style: const pw.TextStyle(fontSize: 8)));
    }

    final rows = <pw.TableRow>[];
    int i = 0;
    for (final e in entries) {
      final p = bowlingTeam.players.firstWhere((x) => x.id == e.key, orElse: () => Player(id: '', name: '?'));
      final balls = e.value.balls;
      final overs = '${balls ~/ 6}.${balls % 6}';
      final econ = balls > 0 ? (e.value.runs / (balls / 6)).toStringAsFixed(1) : '-';

      rows.add(pw.TableRow(
        decoration: pw.BoxDecoration(color: i.isOdd ? _hex(0xFAFAF5) : PdfColors.white),
        children: [
          _cell(p.name, bold: true),
          _cell(overs, color: PdfColors.grey600, align: pw.TextAlign.right),
          _cell('${e.value.runs}', align: pw.TextAlign.right),
          _badgeOrDash(e.value.wickets, _hex(0xFEE2E2), _hex(0xB91C1C)),
          _cell(econ, color: PdfColors.grey600, align: pw.TextAlign.right),
        ],
      ));
      i++;
    }

    return pw.Table(
      border: pw.TableBorder.all(color: _hex(0xECECE4), width: 0.4),
      columnWidths: const {
        0: pw.FlexColumnWidth(2.6),
        1: pw.FlexColumnWidth(0.8),
        2: pw.FlexColumnWidth(0.8),
        3: pw.FlexColumnWidth(0.7),
        4: pw.FlexColumnWidth(0.9),
      },
      children: [
        pw.TableRow(
          decoration: pw.BoxDecoration(color: _hex(0xF7F5EC)),
          children: ['BOWLER', 'O', 'R', 'W', 'ECON']
              .map((h) => pw.Padding(
                    padding: const pw.EdgeInsets.symmetric(horizontal: 4, vertical: 5),
                    child: pw.Text(h, style: pw.TextStyle(fontSize: 7, fontWeight: pw.FontWeight.bold, color: _hex(0x6B6B63))),
                  ))
              .toList(),
        ),
        ...rows,
      ],
    );
  }
}
